apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    project: roxiler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-deployment-pod
  template:
    metadata:
      name: web-deployment-pod
      labels:
        app: web-deployment-pod
    spec:
      
      containers:
        - name: web-container
          image: vishnuprasanna/roxiler-web:{{ .Values.image.tag }}
          ports:
            - name: web-port
              containerPort: 1331
          envFrom:
            - secretRef:
                name: roxiler-secret
          resources:
            limits:
              memory: "512Mi"
              cpu: "126m"
          livenessProbe:
            httpGet:
              path: /
              port: 1331
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 1331
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 3
      initContainers:
        - name: init-container
          image: busybox
          command: ['sh', '-c', 'until nc -z mongo 27017; do echo waiting for roxiler-db-service; sleep 2; done;']
          