version: '3.8'

services:

  web:
    build:
      context: .
    ports:
      - "1331:1331"
    environment:
      DB_USER: root
      DB_PASS: example
      DB_HOST: mongo
      MONGO_INITDB_DATABASE     : stat

  mongo:
    build:
      context: /databasebuild/
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE     : stat
      DB_HOST                   : mongo

#  mongo-express:
#depends_on:
#- mongo
#image: mongo-express
#restart: always
#ports:
#- 8081:8081
#environment:
#ME_CONFIG_MONGODB_ADMINUSERNAME: root
#ME_CONFIG_MONGODB_ADMINPASSWORD: example
#ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
#ME_CONFIG_BASICAUTH: false


