apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    project: roxiler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-deployment-pod
  template:
    metadata:
      name: db-deployment-pod
      labels:
        app: db-deployment-pod
    spec:
      containers:
        - name: mongo-db-container
          image: vishnuprasanna/roxiler-mongo:0.0.4.BETA
          ports:
            - name: db-port
              containerPort: 27017
          envFrom:
            - secretRef:
                name: roxiler-secret
          resources:
            limits:
              memory: "512Mi"
              cpu: "126m"
          # liveness:
          #   httpGet:
          #     path: /
          #     port: 27017
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          #   failureThreshold: 3
          # readiness:
          #   httpGet:
          #     path: /
          #     port: 27017
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
          #   failureThreshold: 3